name: CI

on:
  push:
    branches:
      - main
      - develop
    tags:
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

env:
  APP_JAVA_VERSION: 17
  DOCKER_IMAGE_NAME: mrcraftcod/channel-points-miner

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.APP_JAVA_VERSION }}
          cache: 'gradle'
      - name: Set gradlew executable
        run: chmod +x ./gradlew
      - name: Build project
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble

  tests:
    name: Run tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.APP_JAVA_VERSION }}
          cache: 'gradle'
      - name: Set gradlew executable
        run: chmod +x ./gradlew
      - name: Run tests
        uses: gradle/gradle-build-action@v2.0-beta.4
        with:
          arguments: test
      - name: Generate JaCoCo report
        uses: gradle/gradle-build-action@v2.0-beta.4
        if: always()
        with:
          arguments: jacocoTestReport
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: 'build/test-results/test/*.xml'
      - name: Publish coverage on CodeCov
        uses: codecov/codecov-action@v3
        if: always()
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: build/reports/jacoco/test/jacocoTestReport.xml
          flags: unittests
          name: codecov-github-actions
      - name: Upload JUnit reports
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: junit-test-results
          path: |
            build/test-results/test/*.xml
            build/reports/tests/tests
          if-no-files-found: error
          retention-days: 14
      - name: Upload JaCoCo reports
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: jacoco-test-results
          path: |
            build/reports/jacoco/test/*.xml
            build/reports/jacoco
          if-no-files-found: error
          retention-days: 14

  publish:
    name: Publish on DockerHub
    runs-on: ubuntu-latest
    needs: tests
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.APP_JAVA_VERSION }}
          cache: 'gradle'
      - name: Set gradle permissions
        run: chmod +x gradlew
      - name: Push branch/tag on Docker Hub
        run: ./gradlew jib -PdockerUsername=${{ secrets.DOCKER_USERNAME }} -PdockerPassword=${{ secrets.DOCKER_TOKEN }} -Djib.to.image="${DOCKER_IMAGE_NAME}:${GITHUB_REF##*/}"
      - name: Push latest on Docker Hub
        if: success() && github.ref == 'refs/heads/main'
        run: ./gradlew jib -PdockerUsername=${{ secrets.DOCKER_USERNAME }} -PdockerPassword=${{ secrets.DOCKER_TOKEN }} -Djib.to.image="${DOCKER_IMAGE_NAME}:latest"
