name: "Qodana"

on:
  push:
  workflow_dispatch:

jobs:
  qodana:
    name: "Qodana"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Qodana
        uses: JetBrains/qodana-action@v5.0.2
        with:
          linter: jetbrains/qodana-jvm-community
