name: "Qodana"

on:
  push:
  workflow_dispatch:

jobs:
  qodana:
    name: "Qodana"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Run Qodana
        uses: JetBrains/qodana-action@v4.2.1
        with:
          linter: jetbrains/qodana-jvm-community
